use kaeru_rig::KaeruMemory;
use rig::tool::ToolDyn;

/// Candidate constructors only. The child assembler installs solely the names
/// explicitly granted by its parent. Keep parity with the pinned Kaeru surface.
pub(super) fn embedded_tools(memory: &KaeruMemory, clouds: bool) -> Vec<Box<dyn ToolDyn>> {
    let mut tools: Vec<Box<dyn ToolDyn>> = vec![
        Box::new(memory.awake()),
        Box::new(memory.overview()),
        Box::new(memory.recall()),
        Box::new(memory.search()),
        Box::new(memory.recent()),
        Box::new(memory.neighbours()),
        Box::new(memory.drill()),
        Box::new(memory.trace()),
        Box::new(memory.tagged()),
        Box::new(memory.between()),
        Box::new(memory.surface()),
        Box::new(memory.at()),
        Box::new(memory.history()),
        Box::new(memory.ideas()),
        Box::new(memory.outcomes()),
        Box::new(memory.initiatives()),
        Box::new(memory.jot()),
        Box::new(memory.episode()),
        Box::new(memory.cite()),
        Box::new(memory.task()),
        Box::new(memory.done()),
        Box::new(memory.board()),
        Box::new(memory.set_status()),
        Box::new(memory.board_status()),
        Box::new(memory.link()),
        Box::new(memory.reweight()),
        Box::new(memory.unlink()),
        Box::new(memory.chain()),
        Box::new(memory.why()),
        Box::new(memory.rechain()),
        Box::new(memory.path()),
        Box::new(memory.synthesise()),
        Box::new(memory.layer()),
        Box::new(memory.pin()),
        Box::new(memory.unpin()),
        Box::new(memory.flag()),
        Box::new(memory.close_review()),
        Box::new(memory.claim()),
        Box::new(memory.evidence()),
        Box::new(memory.inconclusive()),
        Box::new(memory.confirm()),
        Box::new(memory.refute()),
        Box::new(memory.settle()),
        Box::new(memory.revise()),
        Box::new(memory.supersede()),
        Box::new(memory.resolve()),
        Box::new(memory.unsettle()),
        Box::new(memory.hygiene()),
        Box::new(memory.reflect()),
        Box::new(memory.lint()),
        Box::new(memory.forget()),
        Box::new(memory.export()),
        Box::new(memory.attach()),
        Box::new(memory.rename_initiative()),
        Box::new(memory.delete_initiative()),
        Box::new(memory.merge_initiative()),
        Box::new(memory.slot()),
        Box::new(memory.slots()),
        Box::new(memory.unslot()),
        Box::new(memory.config()),
        Box::new(memory.clouds_tool()),
    ];
    if clouds {
        tools.extend(vec![
            Box::new(memory.policy()) as Box<dyn ToolDyn>,
            Box::new(memory.share()) as Box<dyn ToolDyn>,
            Box::new(memory.unshare()) as Box<dyn ToolDyn>,
            Box::new(memory.cloud_recall()) as Box<dyn ToolDyn>,
            Box::new(memory.cloud_initiatives()) as Box<dyn ToolDyn>,
            Box::new(memory.pull()) as Box<dyn ToolDyn>,
            Box::new(memory.link_cloud()) as Box<dyn ToolDyn>,
            Box::new(memory.cloud_links()) as Box<dyn ToolDyn>,
            Box::new(memory.sync_review()) as Box<dyn ToolDyn>,
        ]);
    }
    tools
}
